name: WalterDSU/caddy_alidns

on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manually trigger'
        required: true
        type: choice
        options:
          - build

env:
  FORCE_COLOR: 1
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  asuswrt-merlin-build:
    runs-on: ubuntu-22.04
    #concurrency: docker-image
    steps:
    - name: Init Earthly
      uses: WalterDSU/init-earthly-action@main
    - name: Earthly Build
      working-directory: ${{ github.job }}
      run: earthly --allow-privileged --push +all
